"""Paired stats + LaTeX for voxel-symmetry downstream experiment."""
import json
import sys
from pathlib import Path

import numpy as np
from scipy import stats


OUT_DIR = Path("analysis_results/nips_push_voxel_sym")
RESULTS_PATH = OUT_DIR / "all_results.json"


def paired_stats(bl_vals, dg_vals, lower_better=False):
    bl = np.asarray(bl_vals, dtype=float)
    dg = np.asarray(dg_vals, dtype=float)
    mask = np.isfinite(bl) & np.isfinite(dg)
    bl, dg = bl[mask], dg[mask]
    if len(bl) < 3:
        return {"n": int(len(bl)), "too_few": True}
    diff = dg - bl
    pct = (dg.mean() - bl.mean()) / (abs(bl.mean()) + 1e-12) * 100
    t, p_t = stats.ttest_rel(dg, bl)
    try:
        _, p_w = stats.wilcoxon(dg, bl)
    except Exception:
        p_w = float("nan")
    d = diff.mean() / (diff.std(ddof=1) + 1e-12) if len(diff) > 1 else 0.0
    wins = int((dg < bl).sum()) if lower_better else int((dg > bl).sum())
    return {"n": int(len(bl)),
            "bl_mean": float(bl.mean()), "dgr_mean": float(dg.mean()),
            "pct": float(pct), "p_t": float(p_t), "p_w": float(p_w),
            "cohens_d_paired": float(d),
            "win_rate_pct": 100.0 * wins / len(bl)}


def main():
    if not RESULTS_PATH.exists():
        sys.exit(f"Missing {RESULTS_PATH}")
    with open(RESULTS_PATH) as f:
        results = json.load(f)
    print(f"Loaded {len(results)} pairs\n")

    n = len(results)
    bl_cov = sum(1 for r in results if r["baseline"]["success"])
    dg_cov = sum(1 for r in results if r["dgr"]["success"])
    both = [r for r in results if r["baseline"]["success"] and r["dgr"]["success"]]
    print(f"=== Coverage ===\n  baseline: {bl_cov}/{n}  DGR: {dg_cov}/{n}")
    print(f"=== Paired stats on {len(both)}/{n} both-success pairs ===")

    specs = [
        ("iou", "Voxel-Symmetry IoU (V-IoU)", False),  # higher = better
        ("xor", "Volumetric Asymmetry (V-XOR)", True),  # lower = better
    ]
    summary = {"n_pairs_total": n, "coverage": {"baseline": bl_cov, "dgr": dg_cov},
               "n_both_succeeded": len(both), "metrics": {}}
    rows = []
    for key, label, lower_better in specs:
        bl_v = [r["baseline"][key] for r in both]
        dg_v = [r["dgr"][key] for r in both]
        st = paired_stats(bl_v, dg_v, lower_better=lower_better)
        summary["metrics"][key] = st
        if st.get("too_few"):
            continue
        sig = ""
        if st["p_t"] < 1e-4: sig = " ***"
        elif st["p_t"] < 1e-2: sig = " **"
        elif st["p_t"] < 0.05: sig = " *"
        arrow = "↓" if lower_better else "↑"
        print(f"  {label} {arrow}: bl={st['bl_mean']:.4f} dgr={st['dgr_mean']:.4f} "
              f"Δ={st['pct']:+.1f}% p={st['p_t']:.2e} d={st['cohens_d_paired']:+.2f} "
              f"win={st['win_rate_pct']:.1f}%{sig}")
        rows.append((label, lower_better, st))

    # LaTeX
    latex = [
        "% Auto-generated by analyze_voxel_symmetry.py",
        "\\begin{table}[h]",
        "\\centering",
        "\\caption{Volumetric-symmetry downstream validation ($n=" + str(len(both)) + "$ paired meshes across the $37$ symmetry-focused prompts $\\times$ 3 seeds). Voxel-Symmetry IoU (V-IoU) is the IoU between the filled voxel occupancy and its reflection across our estimated bilateral plane; higher is more symmetric. V-XOR is the symmetric-difference ratio; lower is better. Both metrics are structurally independent of $R_\\mathrm{sym}$ (point-Chamfer), $R_\\mathrm{smooth}$ (face-normal Huber), and $R_\\mathrm{compact}$ (surface/volume ratio); they operate on voxel occupancy and volume overlap.}",
        "\\label{tab:voxel_symmetry_downstream}",
        "\\small",
        "\\begin{tabular}{lcccccc}",
        "\\toprule",
        "Metric & Baseline & DGR & $\\Delta\\%$ & $p$ & $d$ & Win \\\\",
        "\\midrule",
    ]
    for label, lower_better, st in rows:
        arrow = "$\\downarrow$" if lower_better else "$\\uparrow$"
        latex.append(
            f"{label} {arrow} & "
            f"{st['bl_mean']:.4f} & {st['dgr_mean']:.4f} & "
            f"{st['pct']:+.1f}\\% & {st['p_t']:.2e} & "
            f"{st['cohens_d_paired']:+.2f} & {st['win_rate_pct']:.0f}\\% \\\\"
        )
    latex += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT_DIR / "per_metric_table.tex").write_text("\n".join(latex) + "\n",
                                                   encoding="utf-8")
    print(f"\n[tex] {OUT_DIR / 'per_metric_table.tex'}")
    with open(OUT_DIR / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)
    print(f"[json] {OUT_DIR / 'summary.json'}")

    print("\n" + "=" * 60)
    iou = summary["metrics"].get("iou", {})
    xor = summary["metrics"].get("xor", {})
    if iou and not iou.get("too_few"):
        ok = iou["pct"] > 3 and iou["p_t"] < 0.05
        v = "SUPPORTED" if ok else ("NULL" if iou["p_t"] >= 0.05 else "WEAK")
        print(f"  V-IoU lifted by {iou['pct']:+.1f}% (p={iou['p_t']:.2e}, "
              f"d={iou['cohens_d_paired']:+.2f}) [{v}]")
    if xor and not xor.get("too_few"):
        ok = xor["pct"] < -5 and xor["p_t"] < 0.05
        v = "SUPPORTED" if ok else ("NULL" if xor["p_t"] >= 0.05 else "WEAK")
        print(f"  V-XOR reduced by {-xor['pct']:+.1f}% (p={xor['p_t']:.2e}, "
              f"d={xor['cohens_d_paired']:+.2f}) [{v}]")
    print("=" * 60)


if __name__ == "__main__":
    main()
