"""Per-category analysis for V-IoU run on all 3 categories (110 prompts).

Extends analyze_voxel_symmetry.py with a category-wise breakdown showing
that V-IoU improves not only on symmetry-focused prompts but also on
smoothness and compactness prompts.
"""
import json
import sys
from pathlib import Path

import numpy as np
from scipy import stats


OUT_DIR = Path("analysis_results/nips_push_voxel_sym_all")
RESULTS_PATH = OUT_DIR / "all_results.json"


def paired_stats(bl, dg):
    bl = np.asarray(bl); dg = np.asarray(dg)
    diff = dg - bl
    pct = (dg.mean() - bl.mean()) / (abs(bl.mean()) + 1e-12) * 100
    t, p_t = stats.ttest_rel(dg, bl)
    try:
        _, p_w = stats.wilcoxon(dg, bl)
    except Exception:
        p_w = float("nan")
    d = diff.mean() / (diff.std(ddof=1) + 1e-12) if len(diff) > 1 else 0.0
    return {"n": len(bl), "bl": float(bl.mean()), "dgr": float(dg.mean()),
            "pct": float(pct), "p_t": float(p_t), "p_w": float(p_w),
            "d": float(d), "wins": int((dg > bl).sum()),
            "win_rate": 100.0 * int((dg > bl).sum()) / len(bl)}


def prompt_cat(prompt, symmetry, smoothness, compactness):
    if prompt in symmetry: return "symmetry"
    if prompt in smoothness: return "smoothness"
    if prompt in compactness: return "compactness"
    return "unknown"


def main():
    if not RESULTS_PATH.exists():
        sys.exit(f"Missing {RESULTS_PATH}")
    with open(RESULTS_PATH) as f:
        results = json.load(f)
    print(f"Loaded {len(results)} pairs\n")

    # Categorize via prompts_gpteval3d
    sys.path.insert(0, "src")
    from prompts_gpteval3d import (SYMMETRY_PROMPTS, SMOOTHNESS_PROMPTS,
                                    COMPACTNESS_PROMPTS)

    both = [r for r in results
            if r["baseline"]["success"] and r["dgr"]["success"]]
    print(f"Success-both: {len(both)}/{len(results)}")

    by_cat = {"symmetry": [], "smoothness": [], "compactness": [], "OVERALL": []}
    for r in both:
        c = prompt_cat(r["prompt"], SYMMETRY_PROMPTS, SMOOTHNESS_PROMPTS,
                       COMPACTNESS_PROMPTS)
        by_cat[c].append(r)
        by_cat["OVERALL"].append(r)

    summary = {"n_total": len(results), "n_valid": len(both), "categories": {}}
    rows = []
    print(f"\n=== V-IoU per category ===")
    print(f"{'Category':<12}{'n':<5}{'bl':<8}{'dgr':<8}{'Δ%':<10}{'p':<12}{'d':<8}{'win%':<6}")
    print("-" * 70)
    for cat in ["symmetry", "smoothness", "compactness", "OVERALL"]:
        rs = by_cat[cat]
        if not rs:
            print(f"{cat:<12}  (empty)")
            continue
        bl_iou = [r["baseline"]["iou"] for r in rs]
        dg_iou = [r["dgr"]["iou"] for r in rs]
        bl_xor = [r["baseline"]["xor"] for r in rs]
        dg_xor = [r["dgr"]["xor"] for r in rs]
        st_iou = paired_stats(bl_iou, dg_iou)
        st_xor = paired_stats(bl_xor, dg_xor)
        summary["categories"][cat] = {"iou": st_iou, "xor": st_xor}
        print(f"{cat:<12}{st_iou['n']:<5}{st_iou['bl']:<8.4f}{st_iou['dgr']:<8.4f}"
              f"{st_iou['pct']:<+10.1f}{st_iou['p_t']:<12.2e}"
              f"{st_iou['d']:<+8.2f}{st_iou['win_rate']:<6.1f}")
        rows.append((cat, st_iou))

    with open(OUT_DIR / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\n[json] {OUT_DIR / 'summary.json'}")

    # LaTeX table
    latex = [
        "% auto-generated by analyze_voxel_symmetry_all.py",
        "\\begin{table}[h]",
        "\\centering \\small",
        f"\\caption{{V-IoU improvements across all three prompt categories (not only symmetry-focused). The effect generalises to smoothness and compactness prompts.}}",
        "\\label{tab:voxel_symmetry_all}",
        "\\begin{tabular}{lccccccc}",
        "\\toprule",
        "Category & $n$ & Baseline & DGR & $\\Delta$ & $p$ & $d$ & Win \\\\",
        "\\midrule",
    ]
    for cat, st in rows:
        label = "\\textbf{Overall}" if cat == "OVERALL" else cat
        latex.append(
            f"{label} & {st['n']} & {st['bl']:.3f} & {st['dgr']:.3f} & "
            f"{st['pct']:+.1f}\\% & {st['p_t']:.2e} & "
            f"{st['d']:+.2f} & {st['win_rate']:.0f}\\% \\\\"
        )
    latex += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT_DIR / "per_category_table.tex").write_text("\n".join(latex) + "\n",
                                                      encoding="utf-8")
    print(f"[tex] {OUT_DIR / 'per_category_table.tex'}")


if __name__ == "__main__":
    main()
