"""
Exp N (v2): Laplacian Smoothing Baseline — reads meshes from exp_k output.
No Shap-E generation needed. CPU-only, ~30min.

Depends on: results/mesh_validity_objs/ (generated by exp_k_full_mesh_validity.py)

Compares:
  baseline         — raw Shap-E output
  diffgeoreward    — DiffGeoReward refined
  lap_light        — Laplacian(iter=5,  lambda=0.3)
  lap_medium       — Laplacian(iter=10, lambda=0.5)
  lap_strong       — Laplacian(iter=20, lambda=0.5)
  lap_extreme      — Laplacian(iter=50, lambda=0.5)

Output: analysis_results/laplacian_vs_dgr/all_results.json
"""
import os, sys, json, time, re
import numpy as np
import torch
from pathlib import Path
from scipy import stats

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
os.chdir(os.path.join(os.path.dirname(__file__), '..'))

from geo_reward import symmetry_reward, smoothness_reward, compactness_reward
from prompts_gpteval3d import SYMMETRY_PROMPTS, SMOOTHNESS_PROMPTS, COMPACTNESS_PROMPTS

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
SEEDS  = [42, 123, 456]
OBJ_DIR = Path("results/mesh_validity_objs")
OUT_DIR = Path("analysis_results/laplacian_vs_dgr")
OUT_DIR.mkdir(parents=True, exist_ok=True)

ALL_PROMPTS = SYMMETRY_PROMPTS + SMOOTHNESS_PROMPTS + COMPACTNESS_PROMPTS
PROMPT_CAT  = {}
for p in SYMMETRY_PROMPTS:   PROMPT_CAT[p] = "symmetry"
for p in SMOOTHNESS_PROMPTS: PROMPT_CAT[p] = "smoothness"
for p in COMPACTNESS_PROMPTS: PROMPT_CAT[p] = "compactness"

LAPLACIAN_CONFIGS = [
    (5,  0.3, "lap_light"),
    (10, 0.5, "lap_medium"),
    (20, 0.5, "lap_strong"),
    (50, 0.5, "lap_extreme"),
]


def slug(text):
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')


def load_obj(path):
    """Load .obj → (vertices: Tensor[V,3], faces: Tensor[F,3])"""
    verts, faces = [], []
    with open(path) as f:
        for line in f:
            if line.startswith('v '):
                verts.append(list(map(float, line.split()[1:4])))
            elif line.startswith('f '):
                idx = [int(x.split('/')[0]) - 1 for x in line.split()[1:4]]
                faces.append(idx)
    v = torch.tensor(verts, dtype=torch.float32, device=DEVICE)
    f = torch.tensor(faces, dtype=torch.long, device=DEVICE)
    return v, f


def laplacian_smooth(vertices, faces, iterations, lamb):
    if faces.ndim != 2 or faces.shape[0] < 4 or faces.shape[1] != 3:
        return vertices.clone()  # degenerate mesh, skip smoothing
    V = vertices.shape[0]
    edges = torch.cat([
        faces[:, [0,1]], faces[:, [1,2]], faces[:, [2,0]],
        faces[:, [1,0]], faces[:, [2,1]], faces[:, [0,2]]
    ], dim=0)
    src, dst = edges[:, 0], edges[:, 1]
    v = vertices.clone()
    for _ in range(iterations):
        ns = torch.zeros_like(v)
        nc = torch.zeros(V, 1, device=DEVICE)
        ns.scatter_add_(0, dst.unsqueeze(1).expand(-1,3), v[src])
        nc.scatter_add_(0, dst.unsqueeze(1), torch.ones(dst.shape[0],1,device=DEVICE))
        nc = nc.clamp(min=1)
        v = (1 - lamb) * v + lamb * (ns / nc)
    return v


def compute_metrics(verts, faces):
    # symmetry_reward signature: (vertices, axis=1)  — no faces argument
    if verts.ndim != 2 or faces.ndim != 2 or faces.shape[0] < 4:
        return dict(symmetry=None, smoothness=None, compactness=None, error="degenerate_mesh")
    try:
        sym  = symmetry_reward(verts).item()
        smo  = smoothness_reward(verts, faces).item()
        com  = compactness_reward(verts, faces).item()
        return dict(symmetry=sym, smoothness=smo, compactness=com)
    except Exception as e:
        return dict(symmetry=None, smoothness=None, compactness=None, error=str(e))


def main():
    ckpt_path = OUT_DIR / "checkpoint.json"
    results   = []
    done_keys = set()
    if ckpt_path.exists():
        with open(ckpt_path) as f:
            results = json.load(f)
        done_keys = {(r["prompt"], r["seed"], r["method"]) for r in results}
        print(f"Resuming: {len(results)} done")

    # All exp_k methods whose OBJs to load and evaluate
    # baseline + diffgeoreward come from DGR training; others are weight ablations
    EXP_K_METHODS = [
        "baseline",
        "diffgeoreward",
        "handcrafted",
        "sym_only",
        "HNC_only",
        "compact_only",
    ]

    t0 = time.time()
    n_missing = 0
    total = (len(ALL_PROMPTS) * len(SEEDS)
             * (len(EXP_K_METHODS) + len(LAPLACIAN_CONFIGS)))

    for prompt in ALL_PROMPTS:
        cat = PROMPT_CAT[prompt]
        ps  = slug(prompt)

        for seed in SEEDS:
            bl_path = OBJ_DIR / "baseline" / cat / f"{ps}_seed{seed}.obj"

            if not bl_path.exists():
                n_missing += 1
                continue

            # Load baseline mesh once (used for Laplacian smoothing)
            try:
                bl_v, bl_f = load_obj(bl_path)
            except Exception as e:
                print(f"  Load error {bl_path}: {e}")
                continue

            # --- all exp_k methods ---
            for method in EXP_K_METHODS:
                key = (prompt, seed, method)
                if key in done_keys:
                    continue
                obj_path = OBJ_DIR / method / cat / f"{ps}_seed{seed}.obj"
                if not obj_path.exists():
                    # method OBJ missing (e.g. exp_k not yet finished for this method)
                    continue
                try:
                    if method == "baseline":
                        v, f = bl_v, bl_f
                    else:
                        v, f = load_obj(obj_path)
                    m = compute_metrics(v, f)
                    results.append(dict(prompt=prompt, seed=seed, method=method,
                                        category=cat, **m))
                    done_keys.add(key)
                except Exception as e:
                    print(f"  {method} error {obj_path}: {e}")

            # --- laplacian variants (applied to baseline mesh) ---
            for iters, lamb, name in LAPLACIAN_CONFIGS:
                key = (prompt, seed, name)
                if key in done_keys:
                    continue
                lap_v = laplacian_smooth(bl_v, bl_f, iters, lamb)
                m = compute_metrics(lap_v, bl_f)
                results.append(dict(prompt=prompt, seed=seed, method=name,
                                    category=cat, laplacian_iter=iters,
                                    laplacian_lambda=lamb, **m))
                done_keys.add(key)

            # checkpoint every 50 records
            if len(results) % 50 == 0:
                with open(ckpt_path, 'w') as f:
                    json.dump(results, f)

    with open(ckpt_path, 'w') as f:
        json.dump(results, f)
    with open(OUT_DIR / "all_results.json", 'w') as f:
        json.dump(results, f, indent=2)

    elapsed = time.time() - t0
    print(f"\nDone: {len(results)} records, {n_missing} missing meshes, {elapsed:.0f}s")

    # ── analysis ──────────────────────────────────────────────────────────────
    print("\n" + "="*60)
    print("LAPLACIAN vs DIFFGEOREWARD")
    print("="*60)

    METHODS = ["baseline", "diffgeoreward",
               "lap_light", "lap_medium", "lap_strong", "lap_extreme"]

    for metric in ["symmetry", "smoothness", "compactness"]:
        print(f"\n--- {metric.upper()} ---")
        print(f"{'Method':<16s} | {'Mean':>9s} | {'Delta%':>8s} | {'N':>5s}")
        print("-" * 45)
        bl_scores = [r[metric] for r in results
                     if r["method"] == "baseline" and r.get(metric) is not None]
        bl_mean = np.mean(bl_scores) if bl_scores else 1.0
        for m in METHODS:
            sc = [r[metric] for r in results
                  if r["method"] == m and r.get(metric) is not None]
            if not sc:
                continue
            delta = (np.mean(sc) - bl_mean) / abs(bl_mean) * 100
            print(f"{m:<16s} | {np.mean(sc):>9.5f} | {delta:>+7.1f}% | {len(sc):>5d}")

    # paired DGR vs best Laplacian
    print("\n--- PAIRED T-TEST: DGR vs lap_medium ---")
    bl_d   = {(r["prompt"],r["seed"]): r for r in results if r["method"]=="baseline"}
    dgr_d  = {(r["prompt"],r["seed"]): r for r in results if r["method"]=="diffgeoreward"}
    lap_d  = {(r["prompt"],r["seed"]): r for r in results if r["method"]=="lap_medium"}
    common = set(dgr_d) & set(lap_d)
    if len(common) > 5:
        for metric in ["symmetry", "smoothness", "compactness"]:
            a = [dgr_d[k][metric] for k in common
                 if dgr_d[k].get(metric) and lap_d[k].get(metric)]
            b = [lap_d[k][metric] for k in common
                 if dgr_d[k].get(metric) and lap_d[k].get(metric)]
            if len(a) < 5:
                continue
            diff = np.array(a) - np.array(b)
            t, p = stats.ttest_rel(a, b)
            d = diff.mean() / diff.std(ddof=1) if diff.std(ddof=1) > 0 else 0
            print(f"  {metric}: DGR mean={np.mean(a):.5f}, Lap mean={np.mean(b):.5f}, "
                  f"diff={diff.mean():+.5f}, t={t:.3f}, p={p:.4e}, d={d:.3f}")

    print(f"\nResults saved to {OUT_DIR}/all_results.json")


if __name__ == "__main__":
    main()
